-- Create strategy_settings table
CREATE TABLE IF NOT EXISTS public."strategy_settings"
(
    strategy_name text COLLATE pg_catalog."default" NOT NULL DEFAULT 'default'::text,
    big_candle_tf numeric DEFAULT 15,
    small_candle_tf numeric DEFAULT 5,
    preferred_breakout_type text COLLATE pg_catalog."default" DEFAULT 'full_candle_breakout'::text,
    breakout_threshold_pct numeric DEFAULT 60,
    option_entry_price_cap numeric DEFAULT 80,
    hedge_entry_price_cap numeric DEFAULT 50,
    num_entry_legs integer DEFAULT 4,
    num_hedge_legs integer DEFAULT 1,
    sl_percentage numeric DEFAULT 20,
    eod_time time without time zone DEFAULT '15:20:00'::time without time zone,
    no_of_lots integer DEFAULT 1,
    lot_size integer DEFAULT 75,
    hedge_exit_entry_ratio numeric DEFAULT 50,
    hedge_exit_multiplier numeric DEFAULT 3,
    leg_profit_pct numeric DEFAULT 84,
    portfolio_profit_target_pct numeric DEFAULT 2,
    portfolio_stop_loss_pct numeric DEFAULT 2,
    portfolio_capital numeric DEFAULT 900000,
    max_reentry_rounds numeric DEFAULT 1,
    sl_type text COLLATE pg_catalog."default" DEFAULT 'regular_system_sl'::text,
    reentry_breakout_type text COLLATE pg_catalog."default" DEFAULT 'full_candle_breakout'::text,
    one_m_candle_tf integer DEFAULT 1,
    entry_candle integer DEFAULT 1,
    box_sl_trigger_pct numeric DEFAULT 25,
    box_sl_hard_pct numeric DEFAULT 35,
    switch_pct numeric(10,2) DEFAULT 20,
    width_sl_pct numeric(10,2) DEFAULT 40,
    CONSTRAINT strategy_settings_pkey PRIMARY KEY (strategy_name),
    CONSTRAINT strategy_settings_preferred_breakout_type_check CHECK (preferred_breakout_type = ANY (ARRAY['full_candle_breakout'::text, 'pct_based_breakout'::text])),
    CONSTRAINT strategy_settings_sl_type_check CHECK (sl_type = ANY (ARRAY['regular_system_sl'::text, 'box_with_buffer_sl'::text]))
);
